### ISSUE TITLE
IBMi-bob custom build on github

### ISSUE THREAD

**Issue by cosentino-smeup** [IBM/vscode-ibmi-projectexplorer#587]
Hello, I build my project with rules which call a custom program on IBMi. 
If I run the build locally from VS code, it works perfectly.

Rules.mk
```
COSANT1.PGM: cosant1.pgm.rpgle 
	${BRPG1}$@${BRPG2}$<${BRPG3}
COSANT2.PGM: cosant2.pgm.rpgle 
	${BRPG1}$@${BRPG2}$<${BRPG3}
```

.env:
```
CURLIB=BOBMIN_C
LIBL=BOBMIN_C BOBMIN QTEMP SMEUP_DAT SMETAB PER_SRVL SMEDEV QGPL
objlib=BOBMIN_C
srclib=BOBMIN
BRPG1=cl "CALL PGM(${srclib}/TEST3CL) PARM(('
BRPG2=' (*CHAR 50)) ('
BRPG3=' (*CHAR 50)) (${srclib} (*CHAR 10)) (${objlib} (*CHAR 10)))"
```

When I push changes on Github however, IBMi-bob doesn't execute my program but the CRTBNDRPG command.

Why it does not do the same thing? How can I make IBMi-bob call my program from Github?

I attached the project zip file and the copy of the log of the deploy step on github

[bob-min.zip](https://github.com/user-attachments/files/16992574/bob-min.zip)
[github deploy step.txt](https://github.com/user-attachments/files/16992665/github.deploy.step.txt)

This is the last and the most important step of our POC because we expect to work with github instead of building the project locally.

Thank you

**Comment by SanjulaGanepola** [comment]
Hello @cosentino-smeup. Taking a look at your project, it looks like you are setting up your project to be built with both `bob` and `gmake`? When you are running the build locally, it is running `makei build` which will use the `Rules.mk` which is why you see the correct behavior you want. However, in your GitHub workflow, it seems you are using `gmake` which will use the root makefile.

Since I assume you are going to be using `bob`, you should first remove the root makefile. Next, to switch to use `bob` in your GitHub workflow, update:
```yaml
- name: Deploy to IBM i
  run: | 
    ici \
      --cmd "mkdir -p './builds/ics_${GITHUB_HEAD_REF}'" \
      --rcwd "./builds/ics_${GITHUB_HEAD_REF}" \
      --push "." \
      --cmd "/QOpenSys/pkgs/bin/gmake BIN_LIB=CMPSYS"
  env:
    IBMI_HOST: ${{ secrets.IBMI_HOST }}
    IBMI_USER: ${{ secrets.IBMI_USER }}
    IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
    IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}
```
to:
```yaml
- name: Deploy to IBM i
  run: | 
    ici \
      --cmd "mkdir -p './builds/ics_${GITHUB_HEAD_REF}'" \
      --rcwd "./builds/ics_${GITHUB_HEAD_REF}" \
      --push "." \
      --cmd "/QOpenSys/pkgs/bin/gmake BIN_LIB=BOBMIN_C"
  env:
    IBMI_HOST: ${{ secrets.IBMI_HOST }}
    IBMI_USER: ${{ secrets.IBMI_USER }}
    IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
    IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}
    objlib: BOBMIN_C
    srclib: BOBMIN
```

In addition, depending on if you decide to continue using environment variables for the issue described [here](https://github.com/IBM/vscode-ibmi-projectexplorer/issues/583#issuecomment-2349217455), you will need to also add `BUILD1`, `BUILD2`, and `BUILD3` in the above step under `env:`. Thus, it may be better to use the solution I described to have it in your `Rules.mk` in which case you will not need to add these environment variables.

**Comment by cosentino-smeup** [comment]
It looks that it's doing something now on github becaus I receive this message:

objlib must be defined first in the environment variable.

This are my environment variables on github:

![image](https://github.com/user-attachments/assets/77bc810a-7c48-4eb5-9f95-28f1c5cae632)

What am I doing wrong?

[github.log](https://github.com/user-attachments/files/16996542/github.log)

**Comment by SanjulaGanepola** [comment]
@cosentino-smeup Can you share here how you specified the deploy step in your yaml file

**Comment by cosentino-smeup** [comment]
This is the entire folder:

[bob-min.zip](https://github.com/user-attachments/files/16996596/bob-min.zip)

**Comment by edmundreinhardt** [comment]
@SanjulaGanepola I didn't have time to look, but make sure the environment variables make it to the target IBM i and not just the Linux vm doing the action

**Comment by SanjulaGanepola** [comment]
@cosentino-smeup Sorry, just noticed I made a mistake in what I originally suggested. Edmund is correct in that the environment variables need to make it to the target IBM i. 

For GitHub actions, there are various ways to store information in variables:
- [Defining environment variables for a single workflow](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#defining-environment-variables-for-a-single-workflow)
- [Defining configuration variables for multiple workflows](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#defining-configuration-variables-for-multiple-workflows)

It looks like you are using the second option in which case you can access them and send it to the target IBM i in your workflow using:

```yaml
- name: Deploy to IBM i
  run: | 
    ici \
      --cmd "mkdir -p './builds/ics_${GITHUB_HEAD_REF}'" \
      --rcwd "./builds/ics_${GITHUB_HEAD_REF}" \
      --push "." \
      --cmd "/QOpenSys/pkgs/bin/makei build -e objlib=${{ vars.OBJLIB }} -e srclib=${{ vars.SRCLIB }}"
  env:
    IBMI_HOST: ${{ secrets.IBMI_HOST }}
    IBMI_USER: ${{ secrets.IBMI_USER }}
    IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
    IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }} 
```
